# Netlify Configuration
# This file configures how Netlify builds and deploys your site

[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  
  # Directory to publish (where the built files are located)
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build environment variables
  NODE_ENV = "production"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "cd frontend && npm install && npm run build"

[context.deploy-preview]
  command = "cd frontend && npm install && npm run build"

[context.branch-deploy]
  command = "cd frontend && npm install && npm run build"
